# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

    config.vm.provider "virtualbox" do |vb|
       vb.memory = "2048"
    end 
    config.disksize.size = '50GB'
  
    config.vm.define "kind" do |o|
      o.vm.box = "ubuntu/bionic64"
      o.vm.hostname = "kind"
      o.vm.network :private_network, ip: "192.168.100.50"
    end
end