---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: omamama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.18
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: omamama
        - name: MYSQL_USER
          value: omamama
        - name: MYSQL_PASSWORD
          value: 8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
        ports:
          - containerPort: 3306