---
kind: Namespace
apiVersion: v1
metadata:
    name: omamama
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: omamama
subjects:
- kind: ServiceAccount
  namespace: omamama
  name: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin