version: '3'
services:
        mysql:
                image: mysql:8.0.18
                ports:
                        - 3306:3306
                volumes:
                        - db-data=/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=rootpass
                        - MYSQL_DATABASE=omamama
                        - MYSQL_USER=omamama
                        - MYSQL_PASSWORD=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
        user:
                build: ./user
                ports:
                        - 9000:9000
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                        - CHYPHER_KEY=RaJ_GCdicC27ABxGQPD-7N@ri3RYqcgR
                depends_on:
                        - 'mysql'
        rate:
                build: ./rate
                ports:
                        - 9001:9001
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                depends_on:
                        - 'mysql'
        present:
                build: ./present
                ports:
                        - 9002:9002
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                depends_on:
                        - 'mysql'
        pair:
                build: ./pair
                ports:
                        - 9004:9004
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                depends_on:
                        - 'mysql'
        send-message:
                build: ./send-message
                ports:
                        - 9003:9003
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                depends_on:
                        - 'mysql'
        get-message:
                build: ./get-message
                ports:
                        - 9006:9006
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                depends_on:
                        - 'mysql'
        card-info:
                build: ./card-info
                ports:
                        - 9005:9005
                environment:
                        - DB_USER=omamama
                        - DB_PASS=8Q*AvwuZKNcqdEPKJWy6ZHyNw_Th-fj_BRdtT_L-EUKQmGXVD3dF7ZsKVa4YfP!n
                        - DB_IP=mysql
                        - DB_PORT=3306
                        - DB_NAME=omamama
                depends_on:
                        - 'mysql'
        bff-api:
                build: ./bff
                ports:
                        - 4000:4000
                environment:
                        - USER=http://user:9000
                        - RATE=http://rate:9001
                        - PRESENT=http://present:9002
                        - SEND_MESSAGE=http://send-message:9003
                        - GET_MESSAGE=http://get-message:9006
                        - PAIR=http://pair:9004
                        - CARD_INFO=http://card-info:9005
                depends_on:
                        - 'user'
                        - 'rate'
                        - 'present'
                        - 'send-message'
                        - 'get-message'
                        - 'pair'
                        - 'card-info'